### ISSUE TITLE
PCB Version 2

### ISSUE THREAD

**Issue by schluderjupp** [luftek/Dekada#1]
The common trace is missing between the pin headers for the 10k resistors.

**Comment by zigastegu** [comment]
Thank you for issue.
I can confirm that design files have a mistake.
Should have run the ERC test. :/
![2016-10-19 20_58_58-3d viewer](https://cloud.githubusercontent.com/assets/1379063/22052072/1f11b62e-dd48-11e6-8127-95e152354cf5.png)

**Comment by zigastegu** [comment]
![36321 img_20170121_105430](https://cloud.githubusercontent.com/assets/1379063/22173703/51768c2c-dfcb-11e6-938b-f69e9399b4e7.jpg)

**Comment by zigastegu** [comment]
Lower soldering station temperature and connect with bridges of solder OR use strand of wire

**Comment by zigastegu** [comment]
Solved with version 0v3 102624f
